-- Crear el usuario
ALTER SESSION SET "_ORACLE_SCRIPT"=TRUE;
-- Crear el usuario
CREATE USER rafa IDENTIFIED BY "123456"
DEFAULT TABLESPACE "USERS"
TEMPORARY TABLESPACE "TEMP";

-- Asignar cuota y permisos bÃ¡sicos
ALTER USER rafa QUOTA UNLIMITED ON USERS;
GRANT CREATE SESSION TO rafa;
GRANT "RESOURCE" TO rafa;
ALTER USER rafa DEFAULT ROLE "RESOURCE";